### PR TITLE
Add wrapper over terminate and getAppContainer calls for simctl

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
This will be needed to finish new simulator startup flow PR for appium-xcuitest-driver

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
@imurchie Can you please check again - I've added one more call, that might be necessary for us

**Comment by imurchie** [comment]
What does the `get_app_container` call do? Is it possible to add some tests for these?

**Comment by mykola-mokhnach** [comment]
@imurchie this shows a path to application bundle installed on simulator:

```
$> xcrun simctl get_app_container booted com.apple.mobilesafari
/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 10.0.simruntime/Contents/Resources/RuntimeRoot/Applications/MobileSafari.app
```

**Comment by imurchie** [comment]
Ah. Ok. And what does "terminate" do? Looking at it's usage it seems like it doesn't just stop an app running?

**Comment by mykola-mokhnach** [comment]
Running 

```
$> xcrun simctl terminate booted com.apple.mobilesafari
```

will for example terminate Safari if it is currently running (or will do nothing if not).

But get_app_container will return non-zero return code if there is no such app with given bundleId installed

**Comment by imurchie** [comment]
Published in `node-simctl@3.5.0`.

**Pull request merged**
