### PR TITLE
Add the hidden appinfo subcommand

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
This should fix system apps detection on Simulator and should help to address issues similar to https://github.com/appium/appium/issues/9102

### CODE REVIEW

**Comment by imurchie** [comment]
Seems like the pasteboard stuff doesn't work with Xcode 9b6. Worked fine with 9b5. :(

**Comment by mykola-mokhnach** [comment]
@imurchie Might a bug in Simulator or we need just to retry/wait longer unit PB content is updated.

**Comment by mykola-mokhnach** [comment]
@imurchie Nevertheless, can we merge this commit, so it is possible to fix system apps detection on Simulator?

**Comment by imurchie** [comment]
Yes. This is broken on master too, so it is not this PR.

**Comment by jamesvanhorn** [comment]
thanks for the quick turnaround on this @mykola-mokhnach @imurchie

**Pull request merged**
